lab50:
  window:   
    - editor
    - readme
    - terminal

  files:
    - !exclude "*"
    - !include "trivia.html"
    - !include "styles.css"

check50: 
  files: &check50_files
    - !require "trivia.html"
    - !require "styles.css"

submit50: 
  files: *check50_files
  style: false