lab50:
  files:
    - !exclude "*"
    - !include "index.html"
    - !include "styles.css"

check50: 
  files: &check50_files
    - !require index.html

submit50: 
  files: *check50_files
  style: false